### ISSUE TITLE
 Failure converting the official Sigma rule YML file

### ISSUE THREAD

**Issue by KnightChaser** [P4T12ICK/Sigma2SplunkAlert#14]
As described in `README.md` of this repository, I downloaded [`sysmon_mimikatz_detection_lsass.yml`](https://github.com/P4T12ICK/Sigma-Rule-Repository/blob/master/detection-rules/T1003/sysmon_mimikatz_detection_lsass.yml) from the official Sigma rule YML file (My system was WSL Ubuntu 22.04 LTS, Windows 11, 64 bit)

I put that file just in the locally cloned repository directory and ran the command below
```shell
./sigma2splunkalert rules/sysmon_mimikatz_detection_lsass.yml
```

And I got a failure from the program without any contextual information.
```
# Failure converting the Sigma File: rules/sysmon_mimikatz_detection_lsass.yml
```

Is there anything wrong with my procedure? Of course, I already installed `PyYAML`(6.0.1) and `Jinja2`(3.1.2) via pip to meet the requirements written in your documentation. I appreciate any help you can provide.

**Comment by rciplinskas** [comment]
Hi, I also bumped into the same issue but solved this failure by installing sigma tools library 

```pip install sigmatools```

as it uses _sigmac_ underneath. When rereading prerequisites page it actually states that sigma needs to be installed. Hopefully that helps :)

**Comment by KnightChaser** [comment]
Thanks for the help!
