### ISSUE TITLE
Feature Request - Alert Action: alert_manager

### ISSUE THREAD

**Issue by a2tf** [P4T12ICK/Sigma2SplunkAlert#3]
Hi P4T12ICK,

As I really appreciate and use Sigma2SplunkAlert, I would like to extend the possible "alert_action" with "alert_manager". I think you know the Tool for Splunk already, it's widely used to track alerts/incidents and start workflows on them.

That would mean a new class for AlertManager action, extend the template and write some other code.

What do you think about my request, would it benefit the purpose of your tool?

I could provide code for review.

a2tf

**Comment by P4T12ICK** [comment]
Hi,

that sounds good for me. 
Yes we have to take a look if a new template is needed or the existing one can be extended.
And we will need new classes holding the data for the Alert Manager.

I think that will be a great improvement. Please go for it. 

Thank you for your contribution.

Best regards,
Patrick
